"use client";
import { useEffect, useState } from "react";
import { BarChart3, FileText, Download } from "lucide-react";
import { motion } from "framer-motion";
import Card from "@/components/ui/Card";
import Button from "@/components/ui/Button";
import LoadingSpinner from "@/components/ui/LoadingSpinner";
import { analyticsService } from "@/services/api";
import { formatDate } from "@/lib/utils";
import { FadeIn, StaggerContainer, StaggerItem } from "@/components/ui/Animations";

export default function ManagementReportsPage() {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    analyticsService.listReports({ limit: 20 }).then((d) => setReports(d.reports || [])).catch(() => {}).finally(() => setLoading(false));
  }, []);

  async function downloadCsv() {
    setExporting(true);
    try {
      const blob = await analyticsService.exportCsv();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "smarthire_analytics.csv";
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      alert("Failed to export CSV");
    } finally {
      setExporting(false);
    }
  }

  if (loading) return <LoadingSpinner className="h-96" size="lg" />;

  return (
    <div className="space-y-6">
      <FadeIn>
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary-500 to-primary-600 flex items-center justify-center shadow-sm">
              <BarChart3 className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-surface-900 dark:text-white">Reports</h1>
              <p className="text-surface-500 dark:text-surface-400 text-sm">View placement reports generated by the admin team</p>
            </div>
          </div>
          <Button onClick={downloadCsv} loading={exporting} variant="ghost" size="sm">
            <Download className="w-4 h-4" />
            Export CSV
          </Button>
        </div>
      </FadeIn>

      {reports.length === 0 ? (
        <FadeIn delay={0.1}>
          <div className="text-center py-16 bg-white dark:bg-surface-800 rounded-2xl border border-surface-200 dark:border-surface-700">
            <div className="w-14 h-14 mx-auto mb-3 rounded-2xl bg-surface-100 dark:bg-surface-700 flex items-center justify-center">
              <BarChart3 className="w-6 h-6 text-surface-400 dark:text-surface-500" />
            </div>
            <p className="text-surface-500 dark:text-surface-400 text-sm font-medium">No reports available. Reports are generated by the Placement Admin team.</p>
          </div>
        </FadeIn>
      ) : (
        <StaggerContainer className="space-y-4">
          {reports.map((report) => (
            <StaggerItem key={report.id}>
              <motion.div whileHover={{ y: -1 }} className="bg-white dark:bg-surface-800 rounded-2xl border border-surface-200 dark:border-surface-700 p-6 hover:shadow-premium transition-all">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-primary-50 dark:bg-primary-950/30 rounded-xl flex items-center justify-center flex-shrink-0">
                    <FileText className="w-5 h-5 text-primary-600 dark:text-primary-400" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-surface-900 dark:text-white">{report.title}</h3>
                    <p className="text-xs text-surface-500 dark:text-surface-400">{report.report_type} • {formatDate(report.created_at)}</p>
                  </div>
                </div>
                {report.data?.statistics && (
                  <div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-3">
                    {[
                      { label: "Students", val: report.data.statistics.total_students },
                      { label: "Placed", val: report.data.statistics.total_placed },
                      { label: "Placement %", val: `${report.data.statistics.placement_percentage}%` },
                      { label: "Companies", val: report.data.statistics.total_companies },
                    ].map(({ label, val }) => (
                      <div key={label} className="bg-surface-50 dark:bg-surface-750 rounded-xl p-3 text-center">
                        <p className="text-xs text-surface-400 dark:text-surface-500">{label}</p>
                        <p className="text-lg font-bold text-surface-800 dark:text-surface-200 mt-1">{val}</p>
                      </div>
                    ))}
                  </div>
                )}
              </motion.div>
            </StaggerItem>
          ))}
        </StaggerContainer>
      )}
    </div>
  );
}
